-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_processing_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_hash text NOT NULL UNIQUE,
  request_text text NOT NULL,
  raw_response jsonb,
  parsed_response jsonb,
  model text,
  prompt_version text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_processing_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_processing_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processing_id uuid NOT NULL,
  rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comments text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_processing_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT ai_processing_feedback_processing_id_fkey FOREIGN KEY (processing_id) REFERENCES public.ai_processing_logs(id)
);
CREATE TABLE public.ai_processing_logs (
  id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'error'::text])),
  email_hash text NOT NULL,
  quote_id uuid,
  subject text,
  processing_time_ms integer NOT NULL,
  model text NOT NULL,
  confidence double precision,
  result jsonb,
  error_message text,
  issues ARRAY,
  ip_address text,
  CONSTRAINT ai_processing_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name character varying NOT NULL,
  record_id uuid NOT NULL,
  action character varying NOT NULL,
  old_values jsonb,
  new_values jsonb,
  user_id uuid,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo integer UNIQUE,
  nome_1 text NOT NULL,
  nome_2 text,
  morada_1 text,
  morada_2 text,
  codigo_postal character varying,
  pais character varying DEFAULT 'PT'::character varying,
  telefone character varying,
  fax character varying,
  email character varying,
  www text,
  contribuinte character varying,
  zona text,
  distrito text,
  tipo_empresa text,
  areas_negocio text,
  vendedor text,
  angariador text,
  origem text,
  mercado character varying,
  situacao character varying DEFAULT 'Ativo'::character varying,
  contabilidade text,
  condicoes_pagamento text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT clientes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  company_name character varying,
  nif character varying UNIQUE,
  email character varying,
  phone character varying,
  mobile character varying,
  website character varying,
  address_line1 character varying,
  address_line2 character varying,
  city character varying,
  postal_code character varying,
  country character varying DEFAULT 'Portugal'::character varying,
  payment_terms character varying DEFAULT '30 dias'::character varying,
  credit_limit numeric DEFAULT 0,
  discount_percentage numeric DEFAULT 0,
  status character varying DEFAULT 'active'::character varying,
  notes text,
  internal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  search_vector tsvector,
  total_quotes integer DEFAULT 0,
  total_value numeric DEFAULT 0,
  last_quote_date date,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.pricing_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  work_type character varying NOT NULL,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  template_data jsonb NOT NULL,
  min_quantity integer DEFAULT 1,
  max_quantity integer,
  valid_from date DEFAULT CURRENT_DATE,
  valid_until date,
  CONSTRAINT pricing_templates_pkey PRIMARY KEY (id),
  CONSTRAINT pricing_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.quote_costs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  name character varying NOT NULL,
  category character varying NOT NULL,
  description text,
  quantity numeric DEFAULT 0,
  unit_cost numeric DEFAULT 0,
  total_cost numeric DEFAULT 0,
  is_automatic boolean DEFAULT false,
  is_editable boolean DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  CONSTRAINT quote_costs_pkey PRIMARY KEY (id),
  CONSTRAINT quote_costs_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quote_works (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  code character varying,
  name character varying NOT NULL,
  description text,
  format character varying,
  dimensions_width numeric,
  dimensions_height numeric,
  paper_type character varying,
  paper_weight numeric,
  print_type character varying,
  finish_type character varying,
  quantity integer NOT NULL DEFAULT 0,
  ft_aberto character varying,
  ft_fechado character varying,
  notes text,
  technical_notes text,
  subtotal numeric NOT NULL DEFAULT 0,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  template_id uuid,
  ai_generated boolean DEFAULT false,
  ai_confidence_score numeric,
  CONSTRAINT quote_works_pkey PRIMARY KEY (id),
  CONSTRAINT quote_works_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_works_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.work_templates(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_number character varying NOT NULL UNIQUE,
  status character varying NOT NULL DEFAULT 'EM ESPERA'::character varying,
  client_id uuid,
  client_name character varying NOT NULL,
  client_phone character varying,
  client_mobile character varying,
  client_email text,
  client_nif character varying,
  client_address text,
  delivery_date date,
  delivery_location text,
  delivery_instructions text,
  payment_terms character varying DEFAULT '30 dias'::character varying,
  validity_period character varying DEFAULT '30 dias'::character varying,
  discount_percentage numeric DEFAULT 0,
  general_notes text,
  internal_notes text,
  subtotal numeric NOT NULL DEFAULT 0,
  profit_margin_percentage numeric DEFAULT 30,
  profit_amount numeric DEFAULT 0,
  tax_rate numeric NOT NULL DEFAULT 23,
  tax_amount numeric DEFAULT 0,
  total_with_tax numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  search_vector tsvector,
  ai_processed boolean DEFAULT false,
  ai_processing_data jsonb,
  at_portugal_text text,
  at_portugal_generated_at timestamp with time zone,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT quotes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.work_costs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_id uuid NOT NULL,
  name character varying NOT NULL,
  category character varying NOT NULL,
  description text,
  quantity numeric DEFAULT 0,
  unit_cost numeric DEFAULT 0,
  total_cost numeric DEFAULT 0,
  is_automatic boolean DEFAULT true,
  is_editable boolean DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pricing_template_id uuid,
  metadata jsonb,
  CONSTRAINT work_costs_pkey PRIMARY KEY (id),
  CONSTRAINT work_costs_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.quote_works(id),
  CONSTRAINT work_costs_pricing_template_id_fkey FOREIGN KEY (pricing_template_id) REFERENCES public.pricing_templates(id)
);
CREATE TABLE public.work_impositions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_id uuid NOT NULL,
  plate_width numeric NOT NULL,
  plate_height numeric NOT NULL,
  piece_width numeric NOT NULL,
  piece_height numeric NOT NULL,
  technical_margin numeric DEFAULT 5.0,
  bleed_margin numeric DEFAULT 3.0,
  pieces_per_width integer NOT NULL,
  pieces_per_height integer NOT NULL,
  total_pieces_per_plate integer NOT NULL,
  plates_needed integer NOT NULL,
  waste_percentage numeric NOT NULL,
  rotation_applied boolean DEFAULT false,
  rotation_angle integer DEFAULT 0,
  print_side character varying DEFAULT 'single'::character varying,
  color_mode character varying DEFAULT '4c'::character varying,
  calculated_at timestamp with time zone DEFAULT now(),
  calculated_by uuid,
  visualization_data jsonb,
  custom_settings jsonb,
  CONSTRAINT work_impositions_pkey PRIMARY KEY (id),
  CONSTRAINT work_impositions_work_id_fkey FOREIGN KEY (work_id) REFERENCES public.quote_works(id),
  CONSTRAINT work_impositions_calculated_by_fkey FOREIGN KEY (calculated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.work_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  work_type character varying NOT NULL,
  default_format character varying,
  default_paper_type character varying,
  default_print_type character varying,
  default_finish_type character varying,
  default_costs jsonb,
  default_imposition_settings jsonb,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  metadata jsonb,
  CONSTRAINT work_templates_pkey PRIMARY KEY (id),
  CONSTRAINT work_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);